language: java

services:
  - postgresql

before_install:
  - chmod +x mvnw

before_script:
  - psql -c 'create database molecious;' -U postgres

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: U+Tk0yfvH6cwvZRmi+0cZMjsB4Elila1hy7r5IHq73IRavqLFQ5u6DB67UwcFVgyCTHDBJJqd8egAHd/kxTCNURrXHAgCnDcrrFndJ1GAPx+JR0CLmzRv7EuxoR8QF+ovRH2nmwNStqmGm3LtplkR60ieLcHO3Hm2DFIP3BS1ms+z4B2ZvbOu50WsARWnkh5BgmD68KD3MsJmmTI97aUguoq1AB+Lr0bWjVQRN13LndynSn0qf16/pfeMA+RdPNWpl6td9UQ2zXgIO4usj+fit6WzZh4nhPy6ukGPBL6wB81zP8z2aCRAeKJbyqwYvy4SEAwaWxEq48FlLgmwbkZW/E7yqTrsbWwDI0XbRi1mi8kpTKGY++l73LUg5/leU5Cb8Jmq6oAWtGrm9yH+TI9aYGHKDZcdN6fm0XFbEIdWOk9K3g8hObcNUCRo/CIPa44KGByKEENyKqrKS8i+dty5gBlPg4JviZvXFgOTrqEZxkwndbRIPuRXq456mFOD8N9fJ5S5u9/Y5Z+uMK5czFPqaWMDEyWLmqtmoLNDHa6/PIfgjePg6kEgfrqph1vxvd5jquMPB2Zvxg7HMNT+hmjjwEwqUdMOR0rAZjeN8kRwQohz9c7sj0vz0piQ0mq7rxd2O/GWEoAjSBXLN9FZH7fky+fIU3vQ2XfK06yD/Fmryc=
